# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NyTimesPopularArticles' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NyTimesPopularArticles

  target 'NyTimesPopularArticlesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NyTimesPopularArticlesUITests' do
    # Pods for testing
  end

end
